AWSTemplateFormatVersion: 2010-09-09
Description: lotuseater
Parameters:
  NetworkStackName:
    Type: String
Resources:
  DatabaseAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group For accessing database
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VPC"
Outputs:
  DatabaseAccessSecurityGroup:
    Description: The subnet ID to use for public web servers
    Value:
      Ref: DatabaseAccessSecurityGroup
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DatabaseAccessSecurityGroup"