AWSTemplateFormatVersion: 2010-09-09
Description: lotuseater
Parameters:
  Vpc:
    Type: String
Resources:
  DatabaseAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group For accessing database
      VpcId: !Ref Vpc
  DBACcessIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      SourceSecurityGroupId: !Ref DatabaseAccessSecurityGroup
      GroupId: !Ref DatabaseAccessSecurityGroup
      IpProtocol: -1
Outputs:
  StackName:
    Value: !Ref AWS::StackName
  DatabaseAccessSecurityGroup:
    Description: The subnet ID to use for public web servers
    Value:
      Ref: DatabaseAccessSecurityGroup