AWSTemplateFormatVersion: "2010-09-09"
Description: serverless auroroa db
Parameters:
  NetworkStackName:
    Type: String
  SecurityGroupStackName:
    Type: String
  DatabaseName:
    Type: String
    Default: 'test'
  PipelineStackName:
    Type: String
Resources:
  MyRDSSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "This is a Secrets Manager secret for an RDS DB instance"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
  myKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: Fn::ImportValue:
                     !Sub "${PipelineStackName}-PipelineRoleArn"
            Action: 'kms:*'
            Resource: '*'
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "db subnetgroup"
      SubnetIds:
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-PrivateSubnet1"
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-PrivateSubnet2"
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: "aurora"
      DatabaseName: !Ref DatabaseName
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSSecret, ':SecretString:password}}' ]]
      EngineMode: serverless
      VpcSecurityGroupIds:
        - Fn::ImportValue:
            !Sub "${SecurityGroupStackName}-DatabaseAccessSecurityGroup"
Outputs:
  DatabaseEndpoint:
    Value: !GetAtt "DBCluster.Endpoint.Address"
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DatabaseEndpoint"
  DatabasePort:
    Value: !GetAtt "DBCluster.Endpoint.Port"
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DatabasePort"
  DatabaseCredentialsSecret:
    Value: !Ref MyRDSSecret
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DatabaseCredentials"
  DatabaseName:
    Value: !Ref DatabaseName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DatabaseName"
