Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  KinesisStreamStackName:
    Type: String
Resources:
  KinesisCollector:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.6
      Handler: index.handler
      Environment:
        Variables:
          STREAM_NAME:
            Fn::ImportValue:
                !Sub "${KinesisStreamStackName}-DeliveryStreamName"
      CodeUri: ./../src
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Action:
                - firehose:PutRecordBatch
              Effect: Allow
              Resource:
                - Fn::ImportValue:
                    !Sub "${KinesisStreamStackName}-DeliveryStreamArn"
      Events:
        ThumbnailApi:
            Type: Api
            Properties:
                Path: /thumbnail
                Method: GET
