Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  KinesisStreamName:
    Type: String
  KinesisStreamArn:
    Type: String
Resources:
  KinesisCollector:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.6
      Handler: lotuseater.index.handler
      Environment:
        Variables:
          STREAM_NAME: !Ref KinesisStreamName
      CodeUri: ./../src
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Action:
                - firehose:PutRecordBatch
              Effect: Allow
              Resource:
                - !Ref KinesisStreamArn
      Events:
        ThumbnailApi:
            Type: Api
            Properties:
                Path: /thumbnail
                Method: GET
Outputs:
  StackName:
    Value: !Ref AWS::StackName
