"""create account table

Revision ID: 1577b1fc43f9
Revises: 
Create Date: 2018-12-20 16:13:42.362440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1577b1fc43f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('timestamp', sa.Numeric(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'value', 'device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples')
    # ### end Alembic commands ###
